FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY pdm /app/pdm

# entrypoint script
COPY docker/run_pdm.sh /app/run_pdm.sh
RUN chmod +x /app/run_pdm.sh

CMD ["/app/run_pdm.sh"]
